# LogHawk Configuration

# Paths to the logs to monitor

log_paths:

  - /var/log/auth.log
  - /var/log/syslog
  - /var/log/nginx/access.log

# File where alerts will be written

alert_log: alerts.log

# Patterns to match (basic threat signatures)
patterns:

  # 🛑 Too Many Failed Logins
  - "Failed password for.*from.*port.*ssh"
  - "401 Unauthorized"

  # ⚠️ Unusual Traffic Spikes (e.g. repetitive hits from same IP)
  
  - "(\\d{1,3}\\.){3}\\d{1,3} - - \\[.*\\] \"GET .*\" 200"

  # 🔥 Critical System Errors
  
  - "CRITICAL"
  - "ERROR"

  # 🦠 Suspicious Script Activity
  
  - "CRON.*CMD=.*sh"
  - "CRON.*CMD=.*wget"
  - "CRON.*CMD=.*curl"
  - "CRON.*CMD=.*python"
